[versions]
# Define the versions
kotlin = "1.7.10"

# Domain
kotlinStdlib = "1.7.10"
inject = "1"

# Data & Presentation
androidCore = "1.7.0"
appcompat = "1.4.2"
material = "1.6.1"
junit = "4.13.2"
testJunit = "1.1.3"
espresso = "3.4.0"

constraintLayout = "2.1.3"
recyclerView = "1.2.1"
shimmer = "0.5.0"
spinkit = "1.4.0"

navigation = "2.3.5"
fragmentResult = "1.3.0"
lifecycle = "2.5.1"
coroutines = "1.5.2"
room = "2.4.1"
hilt = "2.40.5"
retrofit = "2.9.0"
okhttp = "4.9.2"
moshi = "1.9.3"
moshiKotlin = "1.12.0"
moshiConverter = "2.9.0"
gson = "2.9.0"
okttpInterceptor = "4.9.0"
glide = "4.13.0"

kakao = "2.8.4"
circleImageview = "3.1.0"
datastore = "1.0.0"

firebaseBom = "30.4.1"
firebaseMessage = "23.0.8"

[libraries]
# Define the libraries

# Domain(Kotlin Module)
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinStdlib" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "inject" }

# Data & Presentation(Android Module)
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidCore" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
android-material = { module = "com.google.android.material:material", version.ref = "material" }
junit-junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "testJunit" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerView" }

androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-navigation-test = { module = "androidx.navigation:navigation-testing", version.ref = "navigation" }
androidx-fragment-request = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentResult" }

androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }

kotlin-coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutine-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room = { module = "androidx.room:room-ktx", version.ref = "room" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

squareup-retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
squareup-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
squareup-okhttp-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okttpInterceptor" }

converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "moshiConverter" }
moshi-moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshiKotlin" }

kakao-sdk = { module = "com.kakao.sdk:v2-user", version.ref = "kakao" }

circle-imageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleImageview" }
facebook-shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }

datastore-preference = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }

glide-glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

android-spinkit = { module = "com.github.ybq:Android-SpinKit", version.ref = "spinkit" }

gson-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "gson" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessage" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }

[bundles]
# Define bundles/groups of libraries
kotlinx-coroutine = ["kotlin-coroutine-core", "kotlin-coroutine-android"]
androidx-navigation = ["androidx-navigation-fragment", "androidx-navigation-ui"]
lifecycle = ["androidx-lifecycle-viewmodel", "androidx-lifecycle-runtime"]
room = ["androidx-room-runtime", "androidx-room"]
moshi = ["converter-moshi", "moshi-moshi", "moshi-kotlin"]
gson = ["gson-gson", "converter-gson"]
datastore = ["datastore-preference", "datastore-core"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.android", version = "kotlin" }